
import type { Metadata } from "next"; 
import React, { ReactNode } from 'react';
import Header from './Header';
import Footer from './Footer';
import { Geist, Geist_Mono } from "next/font/google"; 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;  
}


const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div>
      <Header />
      <main className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children} 
      </main>
      <Footer />
    </div>
  );
};

export default Layout;

